<?php
$flash = $this->flashMessenger();
$flash->setMessageOpenFormat('<div%s>
<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
 </button>
<div>')->setMessageCloseString('</div></div>');

echo $flash->render('error', array ('alert', 'alert-dismissable', 'alert-danger'));
echo $flash->render('info', array ('alert', 'alert-dismissable', 'alert-info'));
echo $flash->render('default', array ('alert', 'alert-dismissable', 'alert-warning'));
echo $flash->render('success', array ('alert', 'alert-dismissable', 'alert-success'));
?>

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">List</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Activities</a></li>
                    <li class="breadcrumb-item active">Index</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <div class="row">
                            <div class="col-1">
                                <a href="<?php echo $this->url('activities', array('action' => 'add')); ?>" class="">
                                    <i class="fas fa-plus"></i>
                                </a>
                                <i class="fas fa-search displaySearch"></i>
                            </div>
                            <div class="col-10">
                                <div class="row search" style="display: none">
                                    <div class="col-11">
                                        <input class="form-control form-control-sm inputSearch" type="text" id="inputSearch" placeholder="Search">
                                    </div>
                                    <div class="col-1">
                                        <i class="fas fa-search btnSearch"></i>
                                        <i class="fas fa-times btnClose"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="col-1">
                                <i class="fa fa-file-excel-o btnExport" aria-hidden="true"></i>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <table
                            id="gridActivities"
                            class="table table-striped table-hover"
                            data-toggle="table"
                            data-pagination="true"
                            data-sort-name=""
                            data-ajax="ajaxRequest"
                            data-side-pagination="server"
                            data-page-size="20"
                            data-classes="table table-striped table-condensed"
                            data-search="false"
                            data-strict-search="false">
                            <thead>
                            <tr>
                                <th data-sortable="true" data-field="titleActivity">Activity</th>
                                <th data-sortable="true" data-field="descriptionActivity">Description</th>
                                <th data-sortable="true" data-field="totalObservations">Observations</th>
                                <th data-sortable="true" data-field="statusActivity">Status</th>
                                <th data-sortable="true" data-field="branchActivity">Branch</th>
                                <th kdata-sortable="true" data-field="startActivity">Start</th>
                                <th kdata-sortable="true" data-field="endActivity">End</th>
                                <th data-sortable="false" data-field="btnView">View</th>
                                <th data-sortable="false" data-field="btnEdit">Edit</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>