<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Work | Eduardo Neria</title>
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, shrink-to-fit=no')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'img/favicon.ico', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('plugins/jquery-ui-1.12.1.custom/jquery-ui.css'))
            ->prependStylesheet($this->basePath('dist/css/customStyle.css'))
            ->prependStylesheet($this->basePath('dist/css/adminlte.min.css'))
            ->prependStylesheet($this->basePath('plugins/toastr/toastr.min.css'))
            /*->prependStylesheet($this->basePath('plugins/datatables-buttons/css/buttons.bootstrap4.min.css'))*/
            /*->prependStylesheet($this->basePath('plugins/datatables-responsive/css/responsive.bootstrap4.min.css'))*/
            /*->prependStylesheet($this->basePath('plugins/datatables-bs4/css/dataTables.bootstrap4.min.css'))*/
            ->prependStylesheet($this->basePath('plugins/fontawesome-free/css/all.min.css'));
    ?>
    <link href="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.css" rel="stylesheet">
    <?php
        $versionConfig = "1.0.0";

        echo $this->headScript()
            ->prependFile($this->basePath('plugins/jquery-ui-1.12.1.custom/jquery-ui.js'))
            ->prependFile($this->basePath('plugins/jquery/validation/jquery.validate.min.js'))
            ->prependFile($this->basePath('plugins/highcharts/modules/accessibility.js'))
            ->prependFile($this->basePath('plugins/highcharts/modules/export-data.js'))
            ->prependFile($this->basePath('plugins/highcharts/modules/exporting.js'))
            ->prependFile($this->basePath('plugins/highcharts/highcharts-3d.js'))
            ->prependFile($this->basePath('plugins/highcharts/highcharts.js'))
            ->prependFile($this->basePath('dist/js/adminlte.js'))
            ->prependFile($this->basePath('plugins/toastr/toastr.min.js'))
            /*->prependFile($this->basePath('plugins/datatables-buttons/js/buttons.colVis.min.js'))
            ->prependFile($this->basePath('plugins/datatables-buttons/js/buttons.print.min.js'))
            ->prependFile($this->basePath('plugins/datatables-buttons/js/buttons.html5.min.js'))*/
            ->prependFile($this->basePath('plugins/pdfmake/vfs_fonts.js'))
            ->prependFile($this->basePath('plugins/pdfmake/pdfmake.min.js'))
/*            ->prependFile($this->basePath('plugins/datatables-buttons/js/buttons.bootstrap4.min.js'))
            ->prependFile($this->basePath('plugins/datatables-buttons/js/dataTables.buttons.min.js'))
            ->prependFile($this->basePath('plugins/datatables-responsive/js/responsive.bootstrap4.min.js'))
            ->prependFile($this->basePath('plugins/datatables-responsive/js/dataTables.responsive.min.js'))
            ->prependFile($this->basePath('plugins/datatables-bs4/js/dataTables.bootstrap4.min.js'))
            ->prependFile($this->basePath('plugins/datatables/jquery.dataTables.min.js'))*/
            ->prependFile($this->basePath('plugins/bootstrap/js/bootstrap.bundle.min.js'))
            ->prependFile($this->basePath('plugins/jquery/jquery.min.js'));

        if (isset($jsModule)) {
            if ( is_array($jsModule)){
                foreach ($jsModule as $rowJsModule){ ?>
                    <script type="text/javascript" src="<?php echo $this->basePath('dist/js/'.$rowJsModule.'.js?version='.$versionConfig) ?>"></script>
            <?php
                }
            }else{
            ?>
                <script type="text/javascript" src="<?php echo $this->basePath('dist/js/'.$jsModule.'.js?version='.$versionConfig)
            ?>"></script>
            <?php
            }
        } ?>

    <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js"></script>

</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <?php echo $this->partial('navbar'); ?>
        <?php echo $this->partial('sidebar'); ?>

        <div class="content-wrapper">
            <div class="content">
                <div class="container-fluid">
                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
        <aside class="control-sidebar control-sidebar-dark">
        </aside>

        <footer class="main-footer">
            <strong>Copyright &copy; 2021-2021 <a href="https://www.linkedin.com/in/eduardo-neria-apolinar-385983117/" target="_blank">Eduardo Neria</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 1.0.0
            </div>
        </footer>
    </div>
</body>
</html>
