<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <a href="index3.html" class="brand-link">
        <img src="dist/img/logo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="">
        <span class="brand-text font-weight-light">Productivity</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="dist/img/myAvatar.png" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="https://www.linkedin.com/in/eduardo-neria-apolinar-385983117/" target="_blank" class="d-block">Eduardo Neria</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">My Activities</li>
                <li class="nav-item">
                    <a href="pages/kanban.html" class="nav-link">
                        <i class="nav-icon far fa-plus-square"></i>
                        <p>
                            Add Activity
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>