<style>
    @import 'https://code.highcharts.com/css/highcharts.css';

    .highcharts-figure, .highcharts-data-table table {
        min-width: 310px;
        max-width: 800px;
        margin: 1em auto;
    }

    .highcharts-data-table table {
        font-family: Verdana, sans-serif;
        border-collapse: collapse;
        border: 1px solid #EBEBEB;
        margin: 10px auto;
        text-align: center;
        width: 100%;
        max-width: 500px;
    }
    .highcharts-data-table caption {
        padding: 1em 0;
        font-size: 1.2em;
        color: #555;
    }
    .highcharts-data-table th {
        font-weight: 600;
        padding: 0.5em;
    }
    .highcharts-data-table td, .highcharts-data-table th, .highcharts-data-table caption {
        padding: 0.5em;
    }
    .highcharts-data-table thead tr, .highcharts-data-table tr:nth-child(even) {
        background: #f8f8f8;
    }
    .highcharts-data-table tr:hover {
        background: #f1f7ff;
    }


    /* Link the series colors to axis colors */
    .highcharts-color-0 {
        fill: #7cb5ec;
        stroke: #7cb5ec;
    }
    .highcharts-axis.highcharts-color-0 .highcharts-axis-line {
        stroke: #7cb5ec;
    }
    .highcharts-axis.highcharts-color-0 text {
        fill: #7cb5ec;
    }
    .highcharts-color-1 {
        fill: #90ed7d;
        stroke: #90ed7d;
    }
    .highcharts-axis.highcharts-color-1 .highcharts-axis-line {
        stroke: #90ed7d;
    }
    .highcharts-axis.highcharts-color-1 text {
        fill: #90ed7d;
    }


    .highcharts-yaxis .highcharts-axis-line {
        stroke-width: 2px;
    }

</style>
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Dashboard</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item active">Dashboard</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<h5 class="mt-4 mb-2">Info Activities <code>*Sub-activities</code></h5>
<div class="row">
    <div class="col-md-6 col-sm-6 col-12">
        <div class="info-box bg-success">
            <span class="info-box-icon"><i class="far fa-thumbs-up"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">Finished</span>
                <span class="info-box-number">
                    <span class="totalActivitiesFinished">
                        <?php echo $this->partial('loadingHome'); ?>
                    </span> Activities
                </span>

                <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                </div>
                <span class="progress-description">
                  <span class="totalSubActivitiesFinished">
                      <?php echo $this->partial('loadingHome'); ?>
                  </span> Sub-Activities
                </span>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6 col-12">
        <div class="info-box bg-warning">
            <span class="info-box-icon"><i class="far fa-calendar-alt"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">Working</span>
                <span class="info-box-number">
                    <span class="totalActivitiesWorking">
                        <?php echo $this->partial('loadingHome'); ?>
                    </span> Activities
                </span>

                <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                </div>
                <span class="progress-description">
                  <span class="totalSubActivitiesWorking">
                      <?php echo $this->partial('loadingHome'); ?>
                  </span> Sub-Activities
                </span>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6 col-sm-6 col-12">
        <figure class="highcharts-figure">
            <div id="container-chart-columns"></div>
        </figure>
    </div>
    <div class="col-md-6 col-sm-6 col-12">
        <figure class="highcharts-figure">
            <div id="container-chart-pie"></div>
        </figure>
    </div>
</div>